### ISSUE TITLE
Filters cause segfault

### ISSUE THREAD

**Issue by ghost** [cacalabs/toilet#5]
Any filter will cause toilet v0.3 to segfault. See screenshot. Same exact thing happens with current git.

Edit: Fuckin' hell. Github is potato-retarded. Here's the screenshot lol
![untitled](https://cloud.githubusercontent.com/assets/3895638/13276064/a2af468c-da78-11e5-9660-4bdb282f6d5d.png)

**Comment by pterjan** [comment]
Hi, it works fine on all my machines.
Can you provide more information like operating system and ideally a stacktrace?

**Comment by samhocevar** [comment]
Also, what is your version of libcaca?

**Comment by ghost** [comment]
OS: Gentoo
Kernel: 4.4.1-gentoo
libcaca version: 0.99_beta18-r2

I have tried rebuilding libcaca already. Didn't change a thing.

Here's the gdb stack trace:

```
┌──  ~  ──┐
└ $ gdb toilet
GNU gdb (Gentoo 7.10.1 vanilla) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from toilet...(no debugging symbols found)...done.
(gdb) run --gay
Starting program: /usr/bin/toilet --gay
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b17b7d in cucul_free_canvas () from /usr/lib64/libcaca.so.0
(gdb) backtrace 
#0  0x00007ffff7b17b7d in cucul_free_canvas () from /usr/lib64/libcaca.so.0
#1  0x00007ffff7b207fb in ?? () from /usr/lib64/libcaca.so.0
#2  0x00007ffff7b20b7a in cucul_canvas_set_figfont () from /usr/lib64/libcaca.so.0
#3  0x0000000000402642 in ?? ()
#4  0x0000000000401924 in ?? ()
#5  0x00007ffff7793790 in __libc_start_main () from /lib64/libc.so.6
#6  0x00000000004019d9 in ?? ()
(gdb) 
```

**Comment by ghost** [comment]
You have a wrong libcaca, as you can see. Forward this issue to their repo.
